"""empty message

Revision ID: 03cf792fa140
Revises: 05ffef7451f6
Create Date: 2022-07-25 22:29:03.001257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03cf792fa140'
down_revision = '05ffef7451f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('songs', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('songs', 'name')
    # ### end Alembic commands ###
